Python docstrings for connection, logic, query and user packages
dmikhalin/typedb-client-java pull request #1
Opened 2023-09-28 16:02 UTC by krishnangovindraj

2023-09-29 14:30 UTC, dmikhalin requested changes
We need to remove some parentheses from examples, because we transformed some getters to properties.

2023-09-29 14:30 UTC, dmikhalin commented on python/typedb/api/query/query_manager.py
> +            transaction.query().match(query, options)
`query` is a property now.

2023-09-29 14:30 UTC, dmikhalin commented on python/typedb/api/logic/logic_manager.py
> +            transaction.logic().get_rule(label)
`logic` is a property now.

2023-09-29 14:30 UTC, dmikhalin commented on python/typedb/api/user/user.py
> +           driver.users().contains(username)
User manager is also retrieved by property.

2023-09-29 15:35 UTC, krishnangovindraj commented on python/typedb/api/user/user.py
> +           driver.users().contains(username)
Updated.

2023-09-29 15:35 UTC, krishnangovindraj commented on python/typedb/api/logic/logic_manager.py
> +            transaction.logic().get_rule(label)
Updated.

2023-09-29 15:35 UTC, krishnangovindraj commented on python/typedb/api/query/query_manager.py
> +            transaction.query().match(query, options)
Updated.

2023-10-04 13:14 UTC, dmikhalin approved these changes
Thanks for your help!

2023-10-04 13:36 UTC, merged